const countriesByContinent = {
    Africa: {
        "dz": "Argélia",
        "ao": "Angola",
        "bj": "Benin",
        "bw": "Botsuana",
        "bf": "Burkina Faso",
        "bi": "Burundi",
        "cv": "Cabo Verde",
        "cm": "Camarões",
        "cf": "República Centro-Africana",
        "td": "Chade",
        "km": "Comores",
        "cg": "Congo",
        "cd": "República Democrática do Congo",
        "dj": "Djibouti",
        "eg": "Egito",
        "gq": "Guiné Equatorial",
        "er": "Eritreia",
        "sz": "Suazilândia",
        "et": "Etiópia",
        "ga": "Gabão",
        "gm": "Gâmbia",
        "gh": "Gana",
        "gn": "Guiné",
        "gw": "Guiné-Bissau",
        "ke": "Quênia",
        "ls": "Lesoto",
        "lr": "Libéria",
        "ly": "Líbia",
        "mg": "Madagascar",
        "mw": "Malawi",
        "ml": "Mali",
        "mr": "Mauritânia",
        "mu": "Maurício",
        "ma": "Marrocos",
        "mz": "Moçambique",
        "na": "Namíbia",
        "ne": "Níger",
        "ng": "Nigéria",
        "rw": "Ruanda",
        "sh": "Santa Helena, Ascensão e Tristão da Cunha",
        "st": "São Tomé e Príncipe",
        "sn": "Senegal",
        "sc": "Seychelles",
        "sl": "Serra Leoa",
        "so": "Somália",
        "za": "África do Sul",
        "ss": "Sudão do Sul",
        "sd": "Sudão",
        "tz": "Tanzânia",
        "tg": "Togo",
        "tn": "Tunísia",
        "ug": "Uganda",
        "eh": "Saara Ocidental",
        "zm": "Zâmbia",
        "zw": "Zimbábue",
      },
      Asia: {
        "af": "Afeganistão",
        "am": "Armênia",
        "az": "Azerbaijão",
        "bh": "Bahrein",
        "bd": "Bangladesh",
        "bt": "Butão",
        "bn": "Brunei Darussalam",
        "kh": "Camboja",
        "cn": "China",
        "cy": "Chipre",
        "ge": "Geórgia",
        "in": "Índia",
        "id": "Indonésia",
        "ir": "Irã",
        "iq": "Iraque",
        "il": "Israel",
        "jp": "Japão",
        "jo": "Jordânia",
        "kz": "Cazaquistão",
        "kw": "Kuwait",
        "kg": "Quirguistão",
        "la": "República Democrática Popular do Laos",
        "lb": "Líbano",
        "my": "Malásia",
        "mv": "Maldivas",
        "mn": "Mongólia",
        "mm": "Myanmar",
        "np": "Nepal",
        "kp": "Coreia do Norte",
        "om": "Omã",
        "pk": "Paquistão",
        "ps": "Palestina",
        "ph": "Filipinas",
        "qa": "Catar",
        "sa": "Arábia Saudita",
        "sg": "Singapura",
        "kr": "Coreia do Sul",
        "lk": "Sri Lanka",
        "sy": "Síria",
        "tw": "Taiwan",
        "tj": "Tajiquistão",
        "th": "Tailândia",
        "tl": "Timor-Leste",
        "tr": "Turquia",
        "tm": "Turquemenistão",
        "ae": "Emirados Árabes Unidos",
        "uz": "Uzbequistão",
        "vn": "Vietnã",
        "ye": "Iêmen",
    },
    Europe: {
        "ax": "Ilhas Åland",
        "ad": "Andorra",
        "at": "Áustria",        
        "al": "Albânia",        
        "ba": "Bósnia e Herzegovina",
        "be": "Bélgica",
        "bg": "Bulgária",
        "by": "Belarus",
        "cy": "Chipre",
        "ch": "Suíça",
        "cz": "República Tcheca",
        "de": "Alemanha",
        "dk": "Dinamarca",
        "ee": "Estônia",
        "es": "Espanha",
        "fi": "Finlândia",
        "fr": "França",
        "gb": "Reino Unido da Grã-Bretanha e Irlanda do Norte",
        "ge": "Geórgia",
        "gi": "Gibraltar",
        "gr": "Grécia",
        "hr": "Croácia",
        "hu": "Hungria",
        "im": "Ilha de Man",
        "fo": "Ilhas Faroe",
        "ie": "Irlanda",
        "is": "Islândia",
        "it": "Itália",
        "je": "Jersey",
        "xk": "Kosovo",
        "li": "Liechtenstein",
        "lt": "Lituânia",
        "lu": "Luxemburgo",
        "lv": "Letônia",
        "mc": "Mônaco",
        "md": "Moldávia",
        "me": "Montenegro",
        "mk": "Macedônia do Norte",
        "mt": "Malta",
        "nl": "Holanda",
        "no": "Noruega",
        "pl": "Polônia",
        "pt": "Portugal",
        "ro": "Romênia",
        "rs": "Sérvia",
        "sm": "San Marino",
        "ru": "Rússia",
        "se": "Suécia",
        "si": "Eslovênia",
        "sk": "Eslováquia",
        "sm": "San Marino",
        "tr": "Turquia",
        "ua": "Ucrânia",
        "va": "Vaticano",
    },
    South_America: {
        "ar": "Argentina",
        "bo": "Bolívia",
        "br": "Brasil",
        "cl": "Chile",
        "co": "Colômbia",
        "ec": "Equador",
        "fk": "Ilhas Falkland (Malvinas)",
        "gy": "Guiana",
        "pe": "Peru",
        "py": "Paraguai",
        "sr": "Suriname",
        "tt": "Trinidad e Tobago",
        "uy": "Uruguai",
        "ve": "Venezuela",
      },
    North_America: {
        "ai": "Anguilla",
        "ag": "Antígua e Barbuda",
        "aw": "Aruba",
        "bs": "Bahamas",
        "bb": "Barbados",
        "bz": "Belize",
        "bm": "Bermudas",
        "ca": "Canadá",
        "ky": "Ilhas Cayman",
        "cr": "Costa Rica",
        "cu": "Cuba",
        "cw": "Curaçao",
        "dm": "Dominica",
        "do": "República Dominicana",
        "sv": "El Salvador",
        "us": "Estados Unidos da América",
        "gl": "Groenlândia",
        "gd": "Granada",
        "gp": "Guadalupe",
        "gt": "Guatemala",
        "ht": "Haiti",
        "hn": "Honduras",
        "hn": "Honduras",
        "mq": "Martinica",
        "mx": "México",  
        "ms": "Montserrat",        
        "ni": "Nicarágua",
        "pa": "Panamá",
        "pr": "Porto Rico",
        "bl": "São Bartolomeu",
        "kn": "São Cristóvão e Nevis",
        "lc": "Santa Lúcia",
        "pm": "São Pedro e Miquelon",
        "vc": "São Vicente e Granadinas",
        "sx": "Sint Maarten",
        "tc": "Ilhas Turks e Caicos",
        "vg": "Ilhas Virgens Britânicas",
        "vi": "Ilhas Virgens Americanas",
    },
    Oceania: {
        "au": "Austrália",
        "nz": "Nova Zelândia",
        "fj": "Fiji",
        "pg": "Papua Nova Guiné",
        "sb": "Ilhas Salomão",
        "vu": "Vanuatu",
        "nc": "Nova Caledônia",
        "wf": "Wallis e Futuna",
        "ck": "Ilhas Cook",
        "nu": "Niue",
        "to": "Tonga",
        "ws": "Samoa",
        "tk": "Tokelau",
        "fm": "Estados Federados da Micronésia",
        "mh": "Ilhas Marshall",
        "pw": "Palau",
        "ki": "Kiribati",
        "tv": "Tuvalu",
        "nr": "Nauru",
    },
    
}

module.exports = countriesByContinent;